### ISSUE TITLE
Newton-Square-Roots.ipynb not found

### ISSUE THREAD

**Issue by ghost** [mitmath/18335#4]
On MITOPENCOURSEWARE the lecture 1 notebook isn't available.

**Comment by stevengj** [comment]
It's in an older branch:

https://github.com/mitmath/18335/blob/spring21/notes/Newton-Square-Roots.ipynb

**Comment by stevengj** [comment]
I've emailed OCW to let them know to fix their links.  In the meantime, the Spring 2019 version of the course (corresponding to the version linked on github) is at:

https://github.com/mitmath/18335/tree/spring19
